name: book_club
description: A personal book library app built with Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  sqflite: ^2.2.8+4
  path: ^1.8.3
  flutter_staggered_animations: ^1.1.1
  pull_to_refresh: ^2.0.0
  flutter_slidable: ^3.0.0
  google_fonts: ^4.0.4
  fluttertoast: ^8.2.2
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  
  